# Assignment 1 NumPy



In [ ]:
#Import the libraries 
import numpy as np

# Problem 1 
Matrix Manipulations

Lets first create a matrix and perform some manipulations of it.

Using numpy's matrix data structure, define the following matricies:

$$A=\left[ \begin{array}{ccc} 3 & 5 & 9 \\ 3 & 3 & 4 \\ 5 & 9 & 17 \end{array} \right]$$

$$B=\left[ \begin{array}{c} 2 \\ 1 \\ 4 \end{array} \right]$$

After this solve the matrix equation:
$$Ax = B$$

In [21]:
import numpy as np
A = [[1,0,0],[3,3,4],[5,9,17]]
B= [2,1,4]
x=np.linalg.solve(A,B)
Ax=np.matmul(A,x)
print(Ax)

[2. 1. 4.]


# Problem 2
Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element
Input: $$arrayOne = \left[\begin{array}{ccc} 5& 6& 9\\ 21 & 18 & 27\end{array}\right]$$
       $$arrayTwo = \left[\begin{array}{ccc} 15 &33& 24\\ 4 &7& 1\end{array}\right]$$



# Problem 2
Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element
Input: $$arrayOne = \left[\begin{array}{ccc} 5& 6& 9\\ 21 & 18 & 27\end{array}\right]$$
       $$arrayTwo = \left[\begin{array}{ccc} 15 &33& 24\\ 4 &7& 1\end{array}\right]$$



In [14]:
arrayOne = [[5,6,9],[21,18,27]]
arrayTwo = [[15,33,24],[4,7,1]]

sum = np.add(arrayOne,arrayTwo)
print(sum)

print(np.square(sum))

[[20 39 33]
 [25 25 28]]
[[ 400 1521 1089]
 [ 625  625  784]]


# Problem 3
Print max from axis 0 and min from axis 1 from the following 2-D array.\
$$sampleArray = \left[\begin{array}{ccc} 34&43&73 \\ 82&22&12 \\ 53&94&66 \end{array}\right]$$




In [11]:
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

minOfAxisOne = numpy.amin(sampleArray,1)
print(minOfAxisOne)

maxOfAxisZero = numpy.amax(sampleArray,0)
print(maxOfAxisZero)

[34 12 53]
[82 94 73]


# Problem 4
Get the positions where elements of a and b match\
Input:  a = np.array([1,2,3,2,3,4,3,4,5,6])\
b = np.array([7,2,10,2,7,4,9,4,9,8])\
Desired Output: array([1, 3, 5, 7])

In [3]:
import numpy as np
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
a[0],a[2],a[8],b[0]

(1, 3, 5, 7)

# Problem 5
Given 
$$a= \left[\begin{array}{cc} 1&2\\ 3&4 \end{array}\right]$$
$$b = \left[\begin{array}{cc} 5&6 \\ 7&8 \end{array}\right]$$
Obtain c and d
$$c = \left[\begin{array}{cc} 1&2\\ 3&4 \\ 5&6 \\ 7&8 \end{array}\right]$$
$$d = \left[\begin{array}{cccc} 1&2&5&6\\ 3&4&7&8 \end{array}\right]$$

In [27]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

C=np.vstack((A,B))
print(C)

D=np.hstack((A,B))
print(D)




[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
